### ISSUE TITLE
x2 = torch.max(x1, x2), y2 = torch.max(y1, y2) in lib/utils/net.py?

### ISSUE THREAD

**Issue by liuhe2017** [generalized-iou/Detectron.pytorch#6]
HI, thanks for the simple and neatly code, it helps me a lot. However, I have a question about the code in lib/utils/net.py. I can't understand the line "x2 = torch.max(x1, x2), y2 = torch.max(y1, y2)" because if x1 is larger than x2, then x1 and x2 would be the same. Could you help me to explain it?

**Comment by jgwak** [comment]
If `x1` is larger than `x2`, it is not a valid bounding box, and its IoU is undefined. We avoid this situation by defining the IoU in this scenario to be `0`. `x2 = torch.max(x1, x2)` is just a small trick for this.

Closing question.
